tiles:
  base:
  - - 9
    - 8
  - - 10
    - 5
  - - 10
    - 6
  - - 10
    - 7
  - - 10
    - 8
  - - 11
    - 7
  - - 11
    - 8
  - - 12
    - 7
  - - 13
    - 6
  - - 14
    - 6
  - - 15
    - 5
  - - 16
    - 5
  joint:
  - - 12
    - 6
  - - 14
    - 5
  wheel: []
